#ifndef FIGHT_VARIABLESGLOBALES_HPP
#define FIGHT_VARIABLESGLOBALES_HPP

#include <string>
#include <iostream>

#define NOMBRECOMPETENCES 6

using std::string;

enum FIGHT_NomCompetence {  FIGHT_ATTAQUER,  FIGHT_BOULEDEFEU,  FIGHT_MORSURE,  FIGHT_GRIFFE,  FIGHT_BOUCLIER,  FIGHT_POTION };
enum FIGHT_Groupe { FIGHT_GENTIL, FIGHT_MECHANT };
enum FIGHT_NomPotion { FIGHT_PASDENOMPOTION, FIGHT_SOIN, FIGHT_MANA, FIGHT_POISON };
enum FIGHT_Race { FIGHT_HUMAIN, FIGHT_LOUP_GAROU, FIGHT_VAMPIRE, FIGHT_MONSTRE };
enum FIGHT_Profession { FIGHT_SOLDAT, FIGHT_VOLEUR, FIGHT_SORCIER };
enum FIGHT_NomArme {  FIGHT_PASDENOMARME, FIGHT_COUTEAU, FIGHT_PISTOLET, FIGHT_FUSIL };
enum FIGHT_NomArmure { FIGHT_PASDENOMARMURE, FIGHT_VETEMENT, FIGHT_KELVAR };

#endif

